
staffplaytime: '' #staff channel for playtime
serverstatus: '' #server-status channel where it sends a message in the channel for schedule restarts.
ingame-chat: '' #ingame chat from minecraft
staffchat: '' #ingame chat from minecraft that the staff can send messages from discord and server to communicate.
commands: '' #commands channel id
category_id: '' #discord category id used for the ticket system
roles_player_id: '' #player role id
roles_staff_id: '' #staff role id
roles_owner_id: '' #owner role id
guild_id: '' #discord server id
Status_enable: true
permissions:
  - simpleminecraftbot.staff
  - simpleminecraftbot.admin