name: SimpleMinecraftBot
version: '${project.version}'
main: me.minercoffee.simpleminecraftbot.Main
api-version: 1.18
load: STARTUP
commands:
  updatechecker:
    usage: /<command>
  staffcheck:
    usage: /<command>
  sbreload:
    usage: /<command>
  staff:
    usage: /<command>
  staffplaytime:
    usage: /<command>