name: SimpleMinecraftBot
version: 1.75
main: me.minercoffee.simpleminecraftbot.Main
api-version: 1.18
load: STARTUP
commands:
  staffhome:
    usage: /<commands>
    description: provides a temporary home
  updatechecker:
    usage: /<command>
  staffcheck:
    usage: /<command>
  sbreload:
    usage: /<command>
  staff:
    usage: /<command>
  staffplaytime:
    usage: /<command>
  sc:
    usage: /<command>
    aliases:
      - staffchat
      - sc
  ping:
    usage: /<command>
    description: retrieves the player ping
permissions:
  simpleminecraftbot.staff:
    description: All staff related permissions and staff related duties.
    default: false
  simpleminecraftbot.admin:
    description: Admin perms.
    default: false